[package]
name = "todo-backend-rocket"
version = "0.1.0"
authors = ["Chris Cosgriff <chris.cosgriff@gmail.com>"]

[dependencies]
rocket = "0.2.2"
rocket_codegen = "0.2.2"
rocket_contrib = "0.2.2"
serde = "0.9.10"
serde_json = "0.9.8"
serde_derive = "0.9.10"
lazy_static = "0.2.2"
